# **Running Instructions**
Write course id of your preferred course in the selection list to get the time table.

# **Output Instructions**
See the output at the end of the notebook (ofcourse after running all cells).
If two courses appear in the same cell of table
Then there is a clash.

In [ ]:
selection = ["CS 613", "HS 520", "EH 608", "MS 491", "CS 433"]

In [ ]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', None)
url1 = "https://raw.githubusercontent.com/Karthikeyanarla/time_table/master/timeslots.csv"
url2 = "https://raw.githubusercontent.com/Karthikeyanarla/time_table/master/timetable.csv"
timing_dataframe = pd.read_csv(url1)
class_works = pd.read_csv(url2)

In [ ]:
dict_time = {}
list1 = ["Lecture", "Tutorial", "Lab"]
flag = 0
for i in selection:
  index = (class_works["Course Code"] == i).idxmax()
  row = class_works.iloc[index]
  course_name = row["Course Name"]
  for j in list1:
    node = row[j]
    if(type(node) != float):
      node_list = node.split("\n")
      if(len(node_list[0])):
        slot_name = node_list[0].split(",")
        for temp in slot_name:
          temp = temp[:2]
          if temp not in dict_time:
            dict_time[temp] = i + " " + course_name + "-" + j
          else:
            flag = 1
            dict_time[temp] +=  ", " + i + " " + course_name + "-" + j
if(flag):
  print("Choose wisely, there are some clashes")

dummy_dataframe = timing_dataframe.copy()
for rowIndex, row in timing_dataframe.iterrows(): 
    for columnIndex, value in row.items():
        if(value in dict_time):
          index = (timing_dataframe["Slot"] == row[0]).idxmax()
          dummy_dataframe[columnIndex][index] = dict_time[value]
dummy_dataframe

            Slot                                           M                                                                     T                                                                 W                                                                    Th                                                                 F
0    8:30 – 9:50                                          A1                                                                    B1                                                                A2                                                                    C2                                                                B2
1  10:00 - 11:20                                          C1                                      CS 433 Computer Networks-Lecture                                                                E1                                      CS 433 Computer Networks-Lecture                                                                E2
2  11:30 - 12:50                                          F1                                                                    G1                                                                H2                                                                    F2                                 CS 433 Computer Networks-Tutorial
3  13:00 - 14:00                                          T1                                                                    T2                                                                T3                                                                    O1                                                                O2
4  14:00 - 15:20  CS 613 Natural Language Processing-Lecture                                                                    J1                        CS 613 Natural Language Processing-Lecture                                                                    K2                                                                J2
5  15:30 - 16:50                                          K1                            HS 520 Ancient Indian Architecture-Lecture  MS 491 Special topics in Management: Marketing Analytics-Lecture                            HS 520 Ancient Indian Architecture-Lecture  MS 491 Special topics in Management: Marketing Analytics-Lecture
6  17:00 - 18:20                                          H1  EH 608 Biodiversity Conservation and Sustainable Development-Lecture                                                                P1  EH 608 Biodiversity Conservation and Sustainable Development-Lecture                                                                P2